export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'

export const DELETE_TODO = 'DELETE_TODO'

export const ADD_TODO = 'ADD_TODO'